### ISSUE TITLE
Bringing Fengsha in UFS-Aerosols to GEFS-Aerosol

### ISSUE THREAD

**Issue by bbakernoaa** [noaa-oar-arl/UFS-Aerosol-Config#13]
## Case Details: 

From @zhanglikate @perthsb @drpeppurr analysis during the ATOM1 period, I did a preliminary step to bring the fengsha dust code back to what we had in GEFS-Aerosol.  During development, an experimental dataset was used only to develop the initial application of the Fengsha dust emission model in UFS-Aerosol.  There wasn't a direct way to recreate the inputs for FENGSHA from the tiled grid, used in GEFS-Aerosol, to the global grid-independent file used for UFS.  So the data was recreated on a global 0.1x0.1 degree grid starting from the SOILGRIDS 2017 dataset and the Pridgent et al. surface roughness (consistent with GEFS).  The thresholds are set after a calculation of the soil type to be as close to GEFS as possible giving us as close as a possible apple to apple comparison.  

The other thing that needs to be done is a slight code change.  @rmontuoro is creating a pull request to put this back into the authoritative NASA repository but it will take a little time for that to get through.  A new term was brought back from an earlier version of FENGSHA that we used primarily in NAQFC called the Soil Erosion Potential Distribution or sepd.  It is another erosion potential that was supposed to be used in conjunction with the sediment supply map.  However, with the SOILGRIDS 2017 dataset, the Sahara lacks a lot of the silt content which would give low sepd value causing all emissions to be squashed.  The experimental dataset used in development uses the SOILGRIDS 2019 dataset which has a higher silt content over the Sahara and so did not cause as many problems. 

The fix is to set sepd to 1.0 (as in GEFS) and use the new fengsha dust inputs.

## Model Configuration Details 
- Resolution: C96
- Begin Date: 2019-07-01
- End Date: 2019-08-31
- Cold Start: True 
- Forecast length (FHMAX_GFS): 24 hours
- FV3 output: every 12 hours 

## Aerosol Model Configuration

- ANTHRO1 (surface emissions) : CEDS2019
- ANTHRO2 (elevated emissions) : CEDS2019
- SHIP :  CEDS2019
- Biomass Burning: GFAS 
- Aviation: HTAP 
- NH3 Emissions: CEDS2019
- Dust : Fengsha
   * alpha:  2.1
   * gamma: 1
   * input file: /scratch1/NCEPDEV/rstprod/nexus_emissions/FENGSHA/FENGSHA_SOILGRIDS2017_GEFSv12_v1.0.nc
- Sea Salt: 3 
    * scaling factor: .6 (Note that I made a mistake here and didn't include the update that @rmontuoro suggested). 
- AOD output: 1 hours 
- Column Mass output: 3 hours 
- Surface Concentrtation output: every 3 hours 

## Measurements/Models available for comparison

- Compared to MERRA2

Please see this document for figures and comparison to MERRA2 

https://docs.google.com/presentation/d/1xCpcTX-VEn7F7qVAltIyGSgn8Ck9ux6V84UkfNm8zH8/edit?usp=sharing

**Comment by rmontuoro** [comment]
The FENGSHA code change was merged into GOCART's authoritative `develop` branch today.

**Comment by zhanglikate** [comment]
@bbakernoaa  Can you share an example of  your rc file to see how to add this new input data?  Thanks

**Comment by bbakernoaa** [comment]
@zhanglikate yes this was updated in the new develop branch as you are aware of already
