### ISSUE TITLE
UPP updates for UFS-Aerosols

### ISSUE THREAD

**Issue by zhanglikate** [noaa-oar-arl/UFS-Aerosol-Config#18]
@bbakernoaa @jianheRCM @lipan-NOAA @drnimbusrain @rmontuoro @gjfrost @perthsb 

Implement the capability into UPP to read the chemical output from UFS-Aerosols/GEFS-Aerosols NetCDF output and use UPP look-up table to calculate AOD and other optical properties. Please use “nasa_on” option for UFS-Aerosols output and “gocart_on” for GEFS-Aerosols in the scripts/exgfs_atmos_nceppost.sh file.  

A  testing version can be download from branch [ufs-aerosols](https://github.com/zhanglikate/EMC_post/tree/ufs-aerosols) . 
Currently, there is not the look-up table for nitrate, so the total AOD in UPP does not include nitrate.  Will  see if we can find the nitrate look-up table later. Also the nitrate concentration has not yet been added, will add it later with more testing.

I just finished one preliminary testing and I am going to do the other one. Partha did a comparison with the NASA online AOD ( https://drive.google.com/drive/folders/1cL8KurRSpmO_fn4Fsfb0oppnUyIq7x1g, please download to view it if the file is too big). 

The UPP looks working well for AOD calculation after the new implementations, which showed quite similar results as the online AOD calculated by UFS-Aerosols. Generally, the UPP AOD is  a  little bit higher than that of the online AOD. Meanwhile, the UPP does not include the nitrate look-up table,so the UPP total AOD is smaller than that of the online AOD.

You are welcome to test it and let me know if there is any issue. Then I will talk to Meng Wen (UPP  team) to see which branch I need to push these updates. 

Thanks.

**Comment by bbakernoaa** [comment]
@zhanglikate @perthsb I'm having trouble opening the google slides and there isn't an option to download

**Comment by zhanglikate** [comment]
@perthsb Can you update the link? I also can not download it now. Thanks.

**Comment by perthsb** [comment]
Check this now :  
https://docs.google.com/presentation/d/1JMzVFIzwR_WTpP4hoUGKrdMr4zA1Geaq/edit?usp=sharing&ouid=100966050662930876047&rtpof=true&sd=true

**Comment by zhanglikate** [comment]
Still can not open it.

**Comment by zhanglikate** [comment]
@perthsb  Still can not open it.

**Comment by perthsb** [comment]
I split them into small files and put it here.
https://drive.google.com/drive/folders/1cL8KurRSpmO_fn4Fsfb0oppnUyIq7x1g?usp=sharing

Let me know if you can access it or not.

**Comment by bbakernoaa** [comment]
@perthsb thanks that did it

**Comment by bbakernoaa** [comment]
All if this is done I'm going to close it.
