### ISSUE TITLE
case/Expt E0 Firex

### ISSUE THREAD

**Issue by bbakernoaa** [noaa-oar-arl/UFS-Aerosol-Config#19]
## Case Details: 

This is an experimental case run from `July 1, 2020 -> Sept 30th, 2020`.  The model was restarted daily at 0z and forecasted out at 24 hours.  The run uses the UFS-Aerosols branch `feature/p7.1` with the updated inline AOD calculation as well as the fengsha sepd bug fix and new inputs.  

### Model Configuration Details

- fscav_aer: [ '*:0.2' ]
- Resolution: C96 
- Begin Date: ```2019-06-15```
- End Date: ```2016-09-30```
- Cold Start: True
- FHOUT_GFS: 6
- FHMAX_GFS: 24 hour cycling
- na_init=1 
- LEVS: 65
- CCPP suite: FV3_GFS_v16

### Chemical Configuration

- AERO_ExtData file: [AERO_ExtData.rc](https://github.com/noaa-oar-arl/UFS-Aerosol-Config/blob/develop/rc.hera/AERO_ExtData.rc)
- HTAP
 * ANTHRO1 (surface)
 * ANTHRO2 (elevated; energy)
 * SHIP
 * NH3 (Agriculture, residential, energy, transport (road and ship), industry)
- QFED biomass burning
- HTAP - aviation
- FENGSHA dust emissions input file: FENGSHA_SOILGRIDS2017_GEFSv12_v1.0.nc
   * alpha = 2.2
   * gamma = 1.0

### Model output

The runs are completed on hera and the files can be found here: 

- Raw model runs & restart files
`/scratch1/NCEPDEV/rstprod/tmp/DATA/htap_firex_p71/2019*/gfs/fcst.*`
- Output files
`/scratch1/NCEPDEV/rstprod/tmp/COM/htap_firex_p71/gfs.*/00/chem`
`/scratch1/NCEPDEV/rstprod/tmp/COM/htap_firex_p71/gfs.20190701/00/atmos`

**Comment by bbakernoaa** [comment]
@perthsb and @drpreppurr could you please take a look and do some comparisons.  @drpreppurr this should cover the Firex AQ time period.  The location of outputs is shown above. 

FYI @gjfrost

**Comment by perthsb** [comment]
Barry, I looked into inline AOD of your run and compared against ICAP and GEOS5 for August 2019 (as in your output some of July 2019 data are missing).
https://docs.google.com/presentation/d/1BVvZ75cWFlDf5cqh6UPXk1i49FZKI1wE/edit?usp=sharing&ouid=100966050662930876047&rtpof=true&sd=true

**Comment by perthsb** [comment]
@bbakernoaa would you check your grib2 files at 
/scratch1/NCEPDEV/rstprod/tmp/COM/htap_firex_p71/gfs.20190701/00/atmos/ . I do not see any AOD files in 2d grib2 files.

**Comment by bbakernoaa** [comment]
Partha,

I do not have the UPP with the aerosols hooked up.  There will not be any
grib2 files with AOD in them.  Plus the UPP needs additional work to
calculate the total AOD as it currently does not include nitrates.  Please
use the nc4 files in the chem directory using the inline AOD calculation.

**Comment by perthsb** [comment]
Barry,
May be you can look into how @zhanglikate hooked up UPP AOD in her EXP 3 or 4 runs.

**Comment by bbakernoaa** [comment]
@perthsb When @zhanglikate commits the change to the workflow I'll include it but it is too much work with too little time to hack it together for each workflow revision.  We need to proceed in a more inclusive way so that we can all proceed in the same manor.
