### ISSUE TITLE
case/plume-rise-implementation

### ISSUE THREAD

**Issue by bbakernoaa** [noaa-oar-arl/UFS-Aerosol-Config#23]
## Case Details: 

We are repeating the Atom1 case study here to test an initial implementation of a plume rise model in UFS-Aerosols.  Two model runs were completed using the `feature/p7.1-gocart-dev` and `feature/p7.1-gocart-dev-plumerise` branches of UFS-Aerosols.  The plume rise algorithm that was first implemented was the simplified sofiev scheme.  This was done because the code is straightforward and easy to implement. The case should be the same as in #3 

## Model Configuration Details 
- Resolution: C96
- Begin Date: 2016-07-15
- End Date: 2016-08-23
- Cold Start: True 
- Forecast length (FHMAX_GFS): 24 hours
- FV3 output: every 6 hours 

## Aerosol Model Configuration

- ANTHRO1 (surface emissions) : HTAP
- ANTHRO2 (elevated emissions) : HTAP
- SHIP :  HTAP
- Biomass Burning: GBBEPx
- Aviation: HTAP 
- NH3 Emissions: HTAP
- Dust : Fengsha
   * alpha:  2.2
   * gamma: 1
   * input file: 
- Sea Salt: 3 
    * scaling factor: 1 
- AOD output: hourly 
- Column Mass output: 12 hours 

## Measurements/Models available for comparison

@siyuan and @perthsb the model results are here: 

no plumerise: `/scratch1/NCEPDEV/rstprod/tmp/COM/noplume/gfs.201607*/00/chem/`
plumerise: `/scratch1/NCEPDEV/rstprod/tmp/COM/noplume/gfs.2016072*/00/chem/`

preliminary comparison: [google slides](https://docs.google.com/presentation/d/1iK-G68AQzdvxipULUXZ7LX-TMNP-0_ZhY41D4oD2OrY/edit?usp=sharing)

@zhanglikate @lipan-NOAA @gjfrost 

P.S. the no plumerise run is still completing.  Should be done this evening to tomorrow morning.

**Comment by zhanglikate** [comment]
@bbakernoaa The plume-rise module  can only use GBBEPx  emission, or  QFED is also good to be use? Is it used FRP or not? Thanks.

**Comment by bbakernoaa** [comment]
@zhanglikate Sofiev is a FRP based scheme. So we could use it for any biomass burning dataset with FRP. I don't currently have the QFED FRP downloaded. Could you help with that? Once there we could easily add it to the RC files.

**Comment by zhanglikate** [comment]
@bbakernoaa I have no idea about the QFED FRP, either. We  discussed that  before for Shan's project  and  can not find the  FRP  in the  QFED data. That is why  we finally used GFAS in Shan's S2S, which  included FRP.  Anyway I  can take  a look at the code  of  "simplified sofiev scheme" ? Thanks.

**Comment by bbakernoaa** [comment]
@zhanglikate You can see the code [here](https://github.com/GEOS-ESM/GOCART/blob/feature/rmontuoro/sofiev/Process_Library/GOCART2G_Process.F90#L4813)

I think that the QFED data uses the MODIS fire product for FRP.  So I think that we would need to go back and get that.  It isn't included in the QFED files themselves.

**Comment by bbakernoaa** [comment]
@drpeppurr could you please perform the Atom1 evaluation with these?
