### ISSUE TITLE
Questions about cloning/building/running feature/7.1

### ISSUE THREAD

**Issue by andytangborn** [noaa-oar-arl/UFS-Aerosol-Config#25]
@rmontuoro @bbakernoaa @zhanglikate 

I'm not clear on the step to checkout a particular branch. 

I have already cloned:

git clone -b feature/p7.1 --recursive https://github.com/rmontuoro/global-workflow.git 

And to checkout a particular branch, the instructions are:

cd sorc/
sh checkout.sh -c -r <branch> -u https://github.com/rmontuoro/ufs-weather-model.git

followed by

sh build_all.sh -c  (or -a). 

I'm not sure what to use for <branch>. It seems that I have already cloned branch feature/p7.1

Am I missing some steps,  such as (I'm not sure what I need to do with these):

feature/p7.1
Add -u <url> option to checkout.sh to download the ufs-weather-model code from a non-authoritative repository
Add case file for P7.1 (prototype7.1.yaml)

**Comment by bbakernoaa** [comment]
@andytangborn 

have you gotten this working? 

I think that the checkout command should be 

`sh checkout.sh -c -r feature/p7.1-gocart-dev -u https://github.com/rmontuoro/ufs-weather-model.git`

**Comment by andytangborn** [comment]
@Barry Baker - NOAA Affiliate ***@***.***>

Thanks Barry.  I'll try that. I've been working on comparisons between JEDI
aerosol forecasts and MERRA-2, which required some regridding. I'll get
back to this workflow later today.

**Comment by andytangborn** [comment]
@Barry Baker - NOAA Affiliate ***@***.***> @Raffaele Montuoro -
NOAA Affiliate ***@***.***>

I've set up an experiment successfully and I'm just starting to run. The
default resolution seems to be C384. Is that what I should try to run?  I
noticed that there are IC for C384 on 2019070100, but on 2019070200 there
are only ICs for C96.   I'm assuming that IC for both days are needed, as
before.

Andy

**Comment by bbakernoaa** [comment]
@andytangborn The target resolution is C384 127L. But the model can be run at C96 and 64L. Where were you looking for ICs? 

The IC directory for the P7.1 runs are only generated on the 1st and 15th of each month. But Shan has created some for daily forecasting for a different purpose.  

/scratch1/BMC/gsd-fv3-dev/Shan.Sun/judy_ic_only/FV3GFSrun

You can see a larger thread on ICs in issue #15

**Comment by andytangborn** [comment]
Barry,


Thanks. I was looking in
/scratch1/NCEPDEV/nems/Raffaele.Montuoro/data/ICS/FV3ICS/2019070200/gfs/
where I got them before.

But I see all the restarts where you pointed me to.

Andy

**Comment by andytangborn** [comment]
I've gotten an error (see below).  But first I want to make sure I'm
running the right case.  I ran:

aerosol_firex_forecast


and got the error :


20210913 201608.456 ERROR            PET000 ESMF_StateAPI.cppF90:2767
ESMF_StateGet       Not found  -  no ESMF_State found named: AERO

20210913 201608.457 ERROR            PET000 Aerosol_Cap.F90:346       Invalid
object  - Passing error in return code

20210913 201608.457 ERROR            PET000
CHM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:2150       Invalid object  -
Passing error in return code

20210913 201608.457 ERROR            PET000 EARTH Grid
Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2570       Invalid object  -
Phase 'IPDv03p7' Initialize for modelComp 2: CHM did not return ESMF_SUCCESS

20210913 201608.457 ERROR            PET000 EARTH Grid
Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2405       Invalid object  -
Passing error in return code

20210913 201608.457 ERROR            PET000 EARTH Grid
Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2193       Invalid object  -
Passing error in return code

20210913 201608.457 ERROR            PET000 EARTH Grid
Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:472       Invalid object  -
Passing error in return code

20210913 201608.457 ERROR            PET000 MAIN_NEMS.F90:429       Invalid
object  - Aborting NEMS


in the log file:


PET000.ESMF_LogFile


I'm also surprised by the large number of log files:


PET000 to PET311

**Comment by andytangborn** [comment]
I've looked at the build directory a bit more.  It's possible that I should have used:

"sh build_all.sh -a" 

instead of  "sh build_all.sh -c".  Can you confirm that this might be the issue?

I realized after posting my previous comment that the large number of log files were just the different processors. 

@bbakernoaa @rmontuoro

**Comment by bbakernoaa** [comment]
@andytangborn I think that you can use `sh build_all.sh -c` for both fully coupled and atm-aero only

**Comment by andytangborn** [comment]
If that's the case, then I'll still need to find out the cause the error
message :

ESMF_StateAPI.cppF90:2767 ESMF_StateGet       Not found  -  no ESMF_State
found named: AERO

I'm rebuilding using the "-a" flag and will try that.

**Comment by andytangborn** [comment]
I've tried rebuilding using "-a" instead of "-c" with build_all.sh, but I get the same error. It appears that  AERO is not recognized by ESMF, and I think it's likely that my build is incorrect so that AERO is not included.  I expect that there could be a place to look in the config files that might give a clue as to the source of the problem.  Any suggestions would be helpful.

**Comment by bbakernoaa** [comment]
When you look in sorc/ufs_coupled.fd do you see the GOCART directory?

**Comment by andytangborn** [comment]
Yes, it is there.

**Comment by bbakernoaa** [comment]
Andy could you point me to your directory and I'll try to take a look

**Comment by andytangborn** [comment]
Thanks!  It's in:

/scratch1/NCEPDEV/da/Andrew.Tangborn/Workflows/aerosol_7p1/global-workflow

**Comment by andytangborn** [comment]
Hi Barry,  could you point me to your build directory? I'd like to do a
diff on the files and see if I can locate what is wrong with my build.

Andy

**Comment by bbakernoaa** [comment]
/scratch2/NAGAPE/arl/Barry.Baker/gwp71

**Comment by andytangborn** [comment]
Thanks.

**Comment by andytangborn** [comment]
So I do find quite a few differences in config.base :

What I have that's different is

export print_esmf=".true."
export cplfx=".false."
export cplice=".false."
export cplwav=".false."
export cplwav2atm=".false."
export nems_temp="atm_aer"
export CCPP_SUITE="FV3_GFS_v16"


I need to find what I should do differently in the setup/build steps to get
the values you have in your config.base

**Comment by bbakernoaa** [comment]
andy I think that we should set up a chat together so that we can get this
resolved.  It would help to fully understand what is happening.

**Comment by andytangborn** [comment]
Yes, that would be very helpful. This week I just have a meeting from 11-12
on Tuesday, 10:30-11:30 and 1:30-2:30 on Wednesday, nothing on Thursday,
and then 1-2 p.m. on Friday.  Otherwise I'm pretty much open.

Andy

**Comment by andytangborn** [comment]
@bbakernoaa @rmontuoro Ivanka has asked me to start to work on getting DA into the coupled workflow. My understanding is that the first step is to be able to run the system with warm restarts. Is there a newer version that I can try. Last month I got the version "feature/p7.1-gocart-dev " to run for one day, and I'd like to do the same (and perhaps longer with a newer version).

**Comment by bbakernoaa** [comment]
@andytangborn Right now I think that is the latest that we have. I may
potentially have an update for the dust component but it isn't ready yet.
And I don't think that there will be any huge update that would break any
of the DA work that you are doing, at least structurally.

**Comment by andytangborn** [comment]
Ok. I'll go back to running that version.  I did have some problem with
getting the 2nd day to run, and will try it again. But mostly, I'll need to
start to understand where the DA is going to fit into the workflow.

**Comment by bbakernoaa** [comment]
Sounds good.  My two cents would be something like this


201908290000     ics.jgfs_emc_mom6ic                           -   -                   -         -             -
201908290000      ics.jgfs_init_chem                           -   -                   -         -             -
** 201908290000      DA_GOES_HERE                                 -    -                   -         -             - **
201908290000    gfs.forecast.highres                           -      -                   -         -             -
201908290000          gfs.post.p_anl                           -     -                   -         -             -
201908290000          gfs.post.p_000                           -     -                   -         -             -
201908290000          gfs.post.p_006                           -    -                   -         -             -
201908290000          gfs.post.p_012                           -    -                   -         -             -
201908290000          gfs.post.p_018                           -     -                   -         -             -
201908290000          gfs.post.p_024                           -    -                   -         -             -
201908290000       gfs.jgfs_emc_vrfy                           -     -                   -         -             -
201908290000                   final                           -         -                   -         -             -

**Comment by andytangborn** [comment]
Thanks. That points me in the right direction.
