### ISSUE TITLE
case/Exp E0.2 Firex:  Adding Offline MEGAN Biogenic VOC Emissions

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/UFS-Aerosol-Config#28]
## Case Details: 

Please provide a brief description of the case or experiment 
This is an experimental case run from July 1, 2019 -> August 31st, 2019. The model was restarted daily at 0z and forecasted out at 24 hours. The run uses the UFS-Aerosols branch feature/p7.1-gocart-dev with the updated inline AOD calculation as well as the fengsha sepd bug fix and new inputs. The purpose of this case is to test adding Offline MEGAN Biogenic VOC emissions (i.e., BioVOC) for SOA formation in the updated GOCART, and then assess the AOD and AOD OC changes against a default case with without BioVOC (i.e., NoBioVOC) emissions.

## Model Configuration Details 
- Resolution: C96 
- Begin Date: 2019-07-01
- End Date: 2019-08-31
- Cold Start: True
- FHOUT_GFS: 6
- Forecast length (FHMAX_GFS): 24 hour cycling
- na_init=1
- LEVS: 65
- CCPP suite: FV3_GFS_v16
- FV3 output: every 6 hours 

## Aerosol Model Configuration
- AERO_ExtData file: [AERO_ExtData.rc](https://github.com/drnimbusrain/UFS-Aerosol-Config/blob/feature/p7.1-gocart-dev/rc.hera/AERO_ExtData.rc.CEDS2019_biovoc)
- ANTHRO1 (surface emissions) : CEDS 2019
- ANTHRO2 (elevated emissions) : CEDS 2019
- SHIP :  CEDS 2019
- Biomass Burning: QFED where GBBEPx isn't available 
- Aviation: HTAP 
- NH3 Emissions: CEDS 2019
- Biogenic Emissions:  Offline MEGAN 2019
- Dust : Fengsha
   * alpha:  2.2
   * gamma: 1.0
   * input file:  FENGSHA_SOILGRIDS2017_GEFSv12_v1.0.nc
- Sea Salt: 3 
    * scaling factor: 1 
- AOD output: 3 hours 
- Column Mass output: 3 hours 
- Surface Concentrtation output: every 3 hours

**Comment by drnimbusrain** [comment]
Offline MEGAN 2019 Emissions Overview:
==============================================================================

Grid-independent offline biogenic VOC emissions are produced using the [HEMCO MEGAN v2.1 plus Guenther 2012 biogenic emissions extension](http://wiki.seas.harvard.edu/geos-chem/index.php/MEGAN_v2.1_plus_Guenther_2012_biogenic_emissions) at GEOS-FP (0.25° x 0.3125°) meteorology field resolution. These emissions were generated with GEOS-Chem 12.3.0, and further pre-processed by HEMCO/NEXUS for input to UFS-Aerosols. The files were generated using the updated Yuan-processed MODIS LAI [(inYuan_XLAI/v2019-03](https://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/Yuan_XLAI/)).

**Comment by drnimbusrain** [comment]
Preliminary Average August 2019 Isoprene and Other Terpene Emissions:
![Isoprene_Emissions_August_2019](https://user-images.githubusercontent.com/26631222/134012198-768e3df0-0443-4e40-bdbf-b9b74477afc5.png)

![Other_Terpene_Emissions_August_2019](https://user-images.githubusercontent.com/26631222/134012223-99fa45cc-6cc7-42e2-ab94-d75b4e91b4ac.png)

Preliminary Absolute and Relative Difference Plots for BioVOC - NoBioVOC (Average August 2019):
![image](https://user-images.githubusercontent.com/26631222/134412661-cb9a5221-b555-485a-850a-9db77e76aaf1.png)

![AOD_spatial_plot_mean_diff](https://user-images.githubusercontent.com/26631222/132868374-d4158fe4-1477-491a-be83-e28b95f5f78f.png)

**Comment by bbakernoaa** [comment]
@perthsb Could you take a quick look at this and do a comparison to ICAP or MERRA2? 

@drnimbusrain could you add the filepath for the output?

**Comment by drnimbusrain** [comment]
@perthsb Preliminary Total AOD Bias Differences against ICAP (top) and GEOS5 (bottom) (Average August 2019):
![GlbBias_TAOD_BioVOC 201908](https://user-images.githubusercontent.com/26631222/132869055-a956f1ed-286a-4b7f-834c-2232481985e5.png)

There are regions of changed AOD bias in biogenic emission prevalent regions, e.g., the Amazon, Eastern U.S., Europe, and East-Southeast Asia. In most of these regions there are reduced negative biases.

**Comment by drnimbusrain** [comment]
@bbakernoaa See analyses above.  Current output paths on Hera are the following (may have to remove soon due to Hera space limitations):

No BioVOC:   /scratch2/NCEPDEV/naqfc/Patrick.C.Campbell/ufs-aer/COM/develop_p71_test_update_atmos
With BioVOC: /scratch2/NCEPDEV/naqfc/Patrick.C.Campbell/ufs-aer/COM/develop_p71_test_update_atmos_biovoc

**Comment by ghost** [comment]
@bbakernoaa @drnimbusrain Only difference between these two runs is in terms of OC over Amazon fire. 
![GlbBias_OCBCAOD_BioVOC 201908](https://user-images.githubusercontent.com/88152718/132897460-c9616a2e-7b47-4ea1-92a5-f3b90adf5e1f.png)

**Comment by drnimbusrain** [comment]
That is not 100% accurate @perthsb , as these were biogenic emissions changes and not fire emission changes.  Please note, there are regions of changed AOD bias in biogenic emission prevalent regions, e.g.,  the Amazon, Eastern U.S., Europe, and East-Southeast Asia.  In most of these regions there are reduced negative biases.  

@bbakernoaa 
The offline biogenic emissions files for 2019, 2018, 2016, and 2013 are found on Hera at:  /scratch2/NAGAPE/arl/Patrick.C.Campbell/nexus_emissions/MEGAN_OFFLINE_BVOC/v2019-10/%y4/

**Comment by ghost** [comment]
@drnimbusrain that is right.

**Comment by bbakernoaa** [comment]
Thanks @drnimbusrain 

I'm going to close this issue
