### ISSUE TITLE
case/Exp E0.3 Firex:  Testing Sensitivity of GOCART to NH3 Emissions

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/UFS-Aerosol-Config#29]
## Case Details: 

This is an experimental case run from July 1, 2019 -> August 31st, 2019. The model was restarted daily at 0z and forecasted out at 24 hours. The run uses the UFS-Aerosols branch feature/p7.1-gocart-dev with the updated inline AOD calculation as well as the fengsha sepd bug fix and new inputs. The purpose of this case is to test the sensitivity of the latest GOCART branch to turning off NH3 emissions, thus demonstrating impact of NH3 emissions on the nitrate formation module in GOCART.  This case arose from a questions on the impact of changing from CEDS 2014 to CEDS 2019 NH3 emissions, with little to no apparent impact on nitrate AOD in the latest GOCART branch.  Analysis below shows significant changes in NH3 emissions between CEDS 2014 and CEDS 2019.

## Model Configuration Details 
- Resolution: C96
- Begin Date: 2019-07-01
- End Date: 2019-08-31
- Cold Start: True 
- FHOUT_GFS: 6
- Forecast length (FHMAX_GFS): 120 hours
- na_init=1
- LEVS: 65
- CCPP suite: FV3_GFS_v16
- FV3 output: every 6 hours 

## Aerosol Model Configuration
- AERO_ExtData file: [AERO_ExtData.rc](https://github.com/noaa-oar-arl/UFS-Aerosol-Config/blob/develop/rc.hera/AERO_ExtData.rc.CEDS2019)
- ANTHRO1 (surface emissions) : CEDS 2019 (No NH3)
- ANTHRO2 (elevated emissions) : CEDS 2019
- SHIP :  CEDS 2019
- Biomass Burning: QFED where GBBEPx isn't available 
- Aviation: HTAP 
- NH3 Emissions:  None
- Dust : Fengsha
   * alpha:  2.2
   * gamma: 1.0
   * input file:  FENGSHA_SOILGRIDS2017_GEFSv12_v1.0.nc
- Sea Salt: 3 
    * scaling factor: 1 
- AOD output: 3 hours 
- Column Mass output: 3 hours 
- Surface Concentrtation output: every 3 hours

**Comment by drnimbusrain** [comment]
CEDS 2014 NH3 Emissions:
![image](https://user-images.githubusercontent.com/26631222/134397665-e2f5529c-9570-4607-a1c8-8b56a898f6fa.png)

Fractional Change of CEDS 2019 NH3 Emissions:
![image](https://user-images.githubusercontent.com/26631222/134397697-419d504e-47f3-4b0a-91a5-12b06c5a8588.png)

Regional NH3 Sectoral Changes (CEDS 2019-CEDS 2014):
![image](https://user-images.githubusercontent.com/26631222/134397811-215f7c47-e740-405f-87fb-c3743443f583.png)

![image](https://user-images.githubusercontent.com/26631222/134397920-59a787e6-3325-4d48-9f57-c9607b9ad809.png)

**Comment by drnimbusrain** [comment]
While there are appreciable anthropogenic NH3 emissions in CEDS 2019 (and CEDS 2019 - CEDS 2014 differences), turning off the NH3 emissions only has a very small impact on Nitrate and the total AOD (change ~< 0.05):

![image](https://user-images.githubusercontent.com/26631222/134412131-77ead570-d728-4099-b7f9-963fe912daa5.png)

![image](https://user-images.githubusercontent.com/26631222/134408649-a52b224c-f107-4dc0-8d07-edbd1bb0f0e1.png)

Therefore the GOCART Nitrate module does not seem very sensitive to anthropogenic NH3 emissions changes.

**Comment by bbakernoaa** [comment]
Thanks @drnimbusrain.  It doesn't seem that the nitrate component is that sensitive to emission changes.  

I suggest that we close this for now until we have some more advancements on that front.
